### ISSUE TITLE
Structure log output and document error conditions

### ISSUE THREAD

**Issue by heffergm** [opentraffic/datastore#20]
Logging output should be structured and error conditions documented. In production, logs will be streamed to Cloudwatch Logs, where filters will be built to pick up the structured data and turn it into Cloudwatch metrics which can then be used to trigger alarm conditions.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

**Comment by drewda** [comment]
@heffergm still relevant? or can this be closed?

**Comment by heffergm** [comment]
not applicable at this point
