### ISSUE TITLE
Investigate binned histogram-style data model

### ISSUE THREAD

**Issue by drewda** [opentraffic/datastore#28]

**Comment by dnesbitt61** [comment]
Some numbers for relative sizing of data in this model. For Asia:

TileCount = 5087
Maximum # of OSMLR segments in a tile = 155722
Average # of OSMLR segments in a tile = 2373

If we assume that we bin speeds per hour:
720 hours/month 
8760 hours per year.

Some questions when thinking about the histogram format:
What precision do we need for speed (1kph bins, 2kph bins)?
Fixed size or variable size. Fixed size should allow for faster access but larger file sizes. Variable size will allow more compact representation but may be slower access for read/write operations.

If the histogram is fixed size at 500 bytes (max. size I can imagine needing!) then the file sizes for **monthly** tiled data would be:
max: 56GB!
average: 854MB

If we can get this down to 124 bytes per histogram (normalized 0-1 percentage using char and a total count) then the sizes are:
max: 13.9 GB
average: 211 MB

**Comment by zerebubuth** [comment]
It seems like this would be very likely to compress well. I would imagine that for most roads, most buckets are empty, especially during the hours of darkness. So there's a lot of zeros there for compression algorithms to pick up.

There are [techniques](https://lh3.github.io/2014/07/05/random-access-to-zlib-compressed-files/) for adding information to compressed files to support (nearly) random access. This can help recover some of the access time for reads.

This seems like it would be a good distribution format, and perhaps a useful output for downstream query APIs to use. The random ordering of the writes would make persisting this in real-time quite painful. Buffering for an hour would need about 1.4GB of memory for the whole of Asia, and then a whole hour "block" could be written out sequentially.

As I understand it, it would be possible to import historical data - data which isn't current. That would make the buffering scheme less effective, and the writes more random. More randomness is bad for performance. For example, on a modern SSD it's possible to sequentially write 540MB/s, which is 4.4 million 124-byte histograms - the whole of Asia in under 3s. But it's only possible to do around 128 thousand random writes (worst-case, real numbers would depend on how many if those writes could be coalesced into blocks, which depends on write patterning) - Asia would take 94s.

Doing that on a single machine would represent an operational issue, though. And I think we'd want to distribute and replicate storage across several availability zones. One design would be to store the data in a distributed system such as Kafka or Kinesis and produce data dumps such as histograms from processes downstream of that. This would remove the problem of a slow (random) write stalling data being read from the Reporters, and means we don't have to worry about the durability of any data we write downstream.

**Comment by drewda** [comment]
Design document: https://docs.google.com/document/d/14RkZawyLU6LMJN5cMMbfAiICOkdy4-IqlbDILeKAzFA/edit#heading=h.dwprevhqrogt

**Comment by drewda** [comment]
Related: https://github.com/opentraffic/histogram-format-tests

**Comment by drewda** [comment]
Based on findings in https://github.com/opentraffic/histogram-format-tests, we'll have Datastore write and query both FlatBuffer- and ORC-formatted histogram tile files. 

FlatBuffer files will likely power ad-hoc API queries that select small subsets of many tile files.

ORC files will likely power static derived data products (e.g., routing tiles, historical data extracts for the public), which are build by scanning entire tile files.
