### ISSUE TITLE
Produce historical Valhalla Routing Tiles

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/datastore#33]
Need a batch process to convert histogram tiles to historical Valhalla routing tiles.

- [ ] Define tile format:

- Per segment speed (indexed by segment Id within a tile) - perhaps 168 bytes (one byte for speed in kph for each hour of the week).
- Segment - to -Segment Transition Times - this cannot be indexed so easily as each traffic segment may have a variable number of transitions. Each segment Id (single Id within the tile) may have several fixed size records including "to_segment_id" (full Valhalla GraphId since it may not reside in the tile) and 168 bytes for the transition time at each hour of the week.

- [ ] Create Batch Tile Generation Script to read histogram tiles over some range of times.

Strategies for creating historical speed tiles may vary and some configuration control should be supported, for example:

- Aggregated over all weeks of the year over the last 2 years
- Aggregated over a recent time period - last 8 weeks
- Weighted averages over similar time periods from prior years (e.g. to show seasonal averages) along with recent week's data.

**Comment by dnesbitt61** [comment]
Need to make sure transition times are only stored for segment-to-segment transitions that occur at a Valhalla graph node (true intersection, not transitions that occur along edges due to "chunks") or transitions across internal edges (roundabouts, internal intersection edges, and turn channels).

**Comment by drewda** [comment]
Not necessary at this point. Instead users of the Analyst UI will be able to calculate route ETAs against historical speeds in-browser: https://github.com/opentraffic/analyst-ui/issues/93
