### ISSUE TITLE
explore alternatives for lessening the bandwidth/memory/disk size requirements on clients

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/datastore#48]
right now we are writing extracts in json format, they are human readable and everyone knows json. plus it plays well with the browser... that is until a single file is getting in the 1gb range...

so we need to look at alternatives. currently we are talking about two ways to tackle this.

1. a format change from clear text to binary. binary allows us to pack data structures more efficiently but does increase the burden of the client when it comes to understanding/working with the format

2. lessening the geographic extents of a given tile. like by a quarter... level 0 looks like level 1, level 1 looks level 2, level 2 looks like 1/4 the size...

**Comment by drewda** [comment]
Related notes from our earlier call: https://docs.google.com/document/d/1LwK6k8dxau0OsrPFqdrRBtCV_OwFn6Pns4VWAIQK3Pg/edit

**Comment by kevinkreiser** [comment]
So i've been looking at number `1` today to see really quickly what protobuf can do for us. To test it i wrote a protobuf definition that is basically a rip off with slight modification of the proposed json extract format. i updated the time range stuff because i think its more flexible. anyway... heres the definition:

```protobuf 
syntax = "proto2";
package SizeTest;

message SpeedTile {
  
  //this allows us to chunk up large tiles into smaller pieces
  repeated SubTile subtiles = 1;
  message SubTile {
    //tile information, where this is
    optional uint32 level = 1;  //the tile level
    optional uint32 index = 2;  //the tile index

    //what segments will be found in this tile
    optional uint32 startSegmentIndex = 3; //the first segment index in the subtile
                                           //makes up the highest 21 bits of of the segment id

    //time information, when this is
    //Note: that it represent both a single ordinal unit in time (if rangeEnd - rangeStart == unitSize)
    //but also be an average unit over a longer period of time (if rangeEnd - rangeStart > unitSize)
    optional uint32 rangeStart = 4; //epoch start time (inclusive) seconds
    optional uint32 rangeEnd = 5;   //epoch end time (exclusive) seconds
    optional uint32 unitSize = 6;   //target time range seconds, a week would be 604800
    optional uint32 entrySize = 7;  //target time range granularity seconds, an hour would be 3600

    optional string description = 8; //text describing the time period this covers

    repeated Segment segments = 9;          //the segments in order
    repeated NextSegment nextSegments = 10; //all next segments in blocks referenced by above segments

    message Segment {
      optional uint32 referenceSpeed = 1;  //the default speed of the segment
      repeated Entry entries = 2;          //all the entries for the given unit of time
                                           //should be a total of unitSize/entrySize entries
      message Entry {
        optional uint32 speed = 1;            //the average speed
        optional float speedVariance = 2;     //the variance between samples
        optional uint32 prevalence = 3;       //a rough indication of how many samples
        optional uint32 nextSegmentIndex = 4; //an index into the next segment array
        optional uint32 nextSegmentCount = 5; //total next segments for this segment
      }
    }

    message NextSegment {
      optional uint64 id = 1;                 //full mask of tile and level and id
      optional uint32 delay = 2;              //delay in seconds from average speed
      optional float delayVariance = 3;       //variance of delay samples
      optional uint32 queueLength = 4;        //length of any queue on segment
      optional float queueLengthVariance = 5; //variance of queue length samples
    }
  }

}
```

note that the top level is just a repeated field. this is a trick often used in protocol buffer to be able to combine different files into one big fat one. we need this because for example, the level 2 tokyo file is so large it doesnt fit into 8gb of ram (at least in python), even though the resulting file is only 350mb. so what we do is do a subtile at a time, which is just some number of segments that program writing the tile can decide at runtime. the osm format uses this trick and ive used it before in the past. you'll also notice that the segments in here are ordered, its not a map. so to use it you'll need to parse the osmlr segment ids to get the segment index and use that to index into the segments within these tiles. this is actually beneficial, breaking it up this way you could on the client side only have a single speed tile loaded at a time, get the data out of it you needed and then load the next one. you'd never run out of ram and ~~all we'd need to achieve it is to set information in each subtile about the range of ids contained within it~~. ive added information to each subtiile to say what range of ids its over so the client will need to get multiple subtiles per area. it would be benificial then, to iterate over osmlr ids with the smallest segment indexes first and then unload each protobuf as you switch from one to the next.

anyway so i wrote a small python program to simulate data for a given osmlr segments file. that program looks like this:

```python
#!/usr/bin/env python
import segment_pb2
import tile_pb2
import speedtile_pb2

import random
import sys

#try this fat tile: wget https://s3.amazonaws.com/osmlr-tiles/v0.1/pbf/2/000/724/159.osmlr

def getIds(fileName):
  osmlr = tile_pb2.Tile()
  with open(fileName, 'rb') as f:
    osmlr.ParseFromString(f.read())

  #get out the segment ids
  segId = 0
  segmentIds = []
  for entry in osmlr.entries:
    if entry.segment:
      segmentIds.append(segId)
    else:
      segmentIds.append(-1)
    segId += 1

  del osmlr

  return segmentIds

def simulate(segmentIds, fileName, subTileSize=10000):
  random.seed(0)

  #fake a segment for each entry in the osmlr
  tile = None
  subTileCount = 0
  for i, sid in enumerate(segmentIds):
    #its time to write a subtile
    if i % subTileSize == 0:
      if tile is not None:
        name = fileName + '.' + str(subTileCount)
        print 'Writing subtile ' + name
        with open(name, 'wb') as f:
          f.write(tile.SerializeToString())
        print 'Wrote subtile ' + name
        subTileCount += 1
        del subtile
        del tile
      #start up a new tile
      tile = speedtile_pb2.SpeedTile()
      subtile = tile.subtiles.add()
      #geo stuff
      subtile.level = 2 #TODO:
      subtile.index = 724159 #TODO:
      subtile.startSegmentIndex = subTileCount * subTileSize
      #time stuff
      subtile.rangeStart = 1483228800
      subtile.rangeEnd = 1483833600
      subtile.unitSize = 604800
      subtile.entrySize = 3600
      subtile.description = '168 ordinal hours of week 0 of year 2017'

    #continue making fake data
    segment = subtile.segments.add()
    if sid == -1: #need blank one to keep the indices correct
      continue
    segment.referenceSpeed = random.randint(20, 100)
    nextIds = [ (random.randint(0,2**21)<<25)|(subtile.index<<3)|subtile.level for i in range(0, random.randint(0,3)) ]
    for i in range(0, subtile.unitSize/subtile.entrySize):
      entry = segment.entries.add()
      entry.speed = random.randint(20, 100)
      entry.speedVariance = random.uniform(0,1)
      entry.prevalence = random.randint(1, 100)
      entry.nextSegmentIndex = len(subtile.nextSegments)
      entry.nextSegmentCount = len(nextIds)
      for nid in nextIds:
        nextSegment = subtile.nextSegments.add();
        nextSegment = subtile.NextSegment()
        nextSegment.id = nid
        nextSegment.delay = random.randint(0,30)
        nextSegment.delayVariance = random.uniform(0,1)
        nextSegment.queueLength = random.randint(0,200)
        nextSegment.queueLengthVariance = random.uniform(0,1)

  #get the last one written
  if tile is not None:
    name = fileName + '.' + str(subTileCount)
    print 'Writing subtile ' + name
    with open(name, 'wb') as f:
      f.write(tile.SerializeToString())
    print 'Wrote subtile ' + name
    del subtile
    del tile

if __name__ == "__main__":
  print 'getting osmlr segments'
  ids = getIds(sys.argv[1])
  
  print 'simulating 1 week of speeds at hourly intervals for ' + str(len(ids)) + ' segments'
  simulate(ids, sys.argv[2])

  print 'done'
```

before you run it you need to do a few things:

```bash
#get dependencies
sudo apt-get install protobuf-compiler python-protobuf
#get the osmlr protos
wget https://raw.githubusercontent.com/opentraffic/osmlr-tile-spec/master/segment.proto
wget https://raw.githubusercontent.com/opentraffic/osmlr-tile-spec/master/tile.proto
#make python code for all the protos
for f in *.proto; do protoc --python_out . $f; done
#get a sample osmlr tile to create fake data for
wget https://s3.amazonaws.com/osmlr-tiles/v0.1/pbf/0/002/415.osmlr
#run the program
python -u sizetest.py 415.osmlr 415.spd
```

for the above example the final size of the pbf is 95mb and when you compress it with `GZIP=-9 gzip 415.spd` it goes down to 42mb. this is the worst case where we have data for every segment for every hour of every day and next segments as well. i still think this is too big for the browser so we'll probably still have to do number `2` above but this is a start.

flatbuffers might be good too as they require no parsing so even if they are huge they dont take a lot of ram. im not sure about the details of google implementation in javascript and how they achieve it but if it works anything like c++ you can just use fseek and a buffer or a mmap. i think we should figure out that detail before we spend time on flatbuffers though.

**Comment by kevinkreiser** [comment]
in doing the splitting up a given tile into multiple parts (over the id space) i think we've actually achieved number `2` above to some degree. the only part that isnt achieved is that we localize the subtiles to a specific region (since its split over the id space and not geographically). im not sure if this matters but it is another optimization we could try in the original spirit of suggestion number `2`

**Comment by louh** [comment]
OK - I've got this downloaded in browser (so far so good) but I'm having trouble parsing them. I've tried both Mapbox's [pbf](github.com/mapbox/pbf) package and the Dcode [protobuf.js](https://github.com/dcodeIO/protobuf.js), but did not finish trying Google's [own library](https://github.com/google/protobuf/tree/master/js) because

> The API is not well-documented yet.

And a general tendency to refer people to the C code to figure out how anything works. Sigh.

That being said I get type errors.

From `pbf`:

`Unimplemented type: 7`

from `protobufjs`:

`Error: invalid wire type 7 at offset 37`

Any thoughts about this?

**Comment by kevinkreiser** [comment]
@louh im getting the same error in the browser as well. give me a bit to figure it out..

**Comment by kevinkreiser** [comment]
@louh i figured it out. at first i was getting the same error as you, and i thought it was because maybe i had a different version of the pbf up there since i was doing so many quick changes in a short period of time. so i refreshed them with the latest definition and still it didnt work. then i added some code to load them from disk in the browser and that worked and im not sure what i changed (typical js story) but the xhr version worked after that. anyway here is the code:

```javascript
<!DOCTYPE html>
<html>
<head>
  <title>test decode pbf</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <textarea id="info" rows="4" cols="50"></textarea></br>

  <script src="https://cdn.rawgit.com/dcodeIO/protobuf.js/6.8.0/dist/protobuf.js"></script>

  <script>
    var parseProto = function(bytes) {
      protobuf.load('https://s3.amazonaws.com/speed-extracts/speedtile.proto', function(err, root) {
        //couldnt parse proto definition
        if(err) throw err;
        //get the message type
        var SpeedTile = root.lookupType('SpeedTile');
        //parse the binary data into an object
        var speedTile = SpeedTile.decode(bytes);
        //do rudimentary stuff with the object
        for(subTile of speedTile.subtiles)
          document.getElementById("info").textContent += subTile.segments.length + ' segments \n';
      });
    };
  </script>

  <script>
    var getByteBufferUrl = function(url, callback) {
      var xhr = new XMLHttpRequest();
      xhr.open('GET', url, true);
      xhr.responseType = 'arraybuffer';

      xhr.onload = function(e) {
        if(this.status == 200) {
          //let the callback do something with the blob
          callback(new Uint8Array(this.response));
        }
      };

      xhr.send();
    }

    //try from the internet
    getByteBufferUrl('https://s3.amazonaws.com/speed-extracts/2017/0/0/002/415.spd.0.gz', parseProto);
  </script>

<!--
  <input type="file" id="files" name="files[]" multiple />
  <script>
    var getByteBufferFile = function(file, callback) {
      var reader = new FileReader();
      reader.onload = function() {
        callback(new Uint8Array(this.result));
      }
      reader.readAsArrayBuffer(file);
    }

    //try from file
    document.getElementById('files').addEventListener('change', function(e) {
      getByteBufferFile(e.target.files[0], parseProto);
    }, false);
  </script>
-->

</body>
</html>
```

**Comment by drewda** [comment]
@kevinkreiser @louh shall we close this, now that PBFs are being created in Datastore and parsed successfully by Analyst UI?

**Comment by louh** [comment]
👍
