### ISSUE TITLE
Produce Reference Speed Tiles

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/datastore#58]
Need a process to periodically query histogram tiles to create "reference" speed information. 

Reference speeds will present the speed at various percentile within a sorted list of speed observations. Having several percentile values will allow users to see how variable speeds are across all hours of the week. An analysis application can choose one of the percentile readings to use as a reference speed when comparing different hourly speed values.

**Comment by drewda** [comment]
Done.

Documentation is underway #78
